version: '3.4'
services:
  pwa-gateway:
    build:
      context: .
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: "${DOCKER_REGISTRY}wikitolearn/pwa-gateway"
    environment:
      KEYCLOAK_URI: ${KEYCLOAK_URI}
      KEYCLOAK_AUTH_REALM: ${KEYCLOAK_AUTH_REALM}
      COURSE_MIDTIER_URI: ${COURSE_MIDTIER_URI}
      SERVICE_PORT: ${SERVICE_PORT}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
