zuul:
  prefix: /api/v1
  sensitive-headers: Cookie,Set-Cookie
  routes:
    courses:
      url: ${COURSE_MIDTIER_URI}/courses
      path: /courses/**
    pages:
      url: ${COURSE_MIDTIER_URI}/pages
      path: /pages/**
security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3
            user-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/userinfo
            token-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/token/introspect
            prefer-token-info: false
            jwt:
                key-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}
logging:
  pattern:
     file: '%d{"yyyy-MM-dd HH:mm:ss,SSS"} %-5level [%c] \(%thread\) : %msg%n'
spring:
  application:
    name: PWAGateway
  output:
    ansi:
      enabled: DETECT
server:
  port: ${SERVICE_PORT}
