# Spring properties
spring:
  application:
    name: PWAGateway
  output:
    ansi:
      enabled: DETECT

# Management properties
management:
  endpoints:
    web:
      base-path: /_meta
      path-mapping:
        health: status
      exposure:
        include: health,info,metrics
  health:
    defaults:
      enabled: false

# Zuul properties
zuul:
  sslHostnameValidationEnabled: false
  prefix: /api/v1
  sensitive-headers: Cookie,Set-Cookie
  routes:
    history:
      url: ${COURSE_MIDTIER_URI}/history/courses
      path: /history/courses/**
    courses:
      url: ${COURSE_MIDTIER_URI}/courses
      path: /courses/**
    chapters:
      url: ${COURSE_MIDTIER_URI}/chapters
      path: /chapters/**
    pages:
      url: ${COURSE_MIDTIER_URI}/pages
      path: /pages/**

# Security properties
security:
    oauth2:
        resource:
            user-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/userinfo
            token-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/token/introspect
            prefer-token-info: false
            jwk:
              key-set-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/certs
              
# Loggin properties
logging:
  pattern:
     file: '%d{"yyyy-MM-dd HH:mm:ss,SSS"} %-5level [%c] \(%thread\) : %msg%n'
     console: '%d{"yyyy-MM-dd HH:mm:ss,SSS"} %-5level [%c] \(%thread\) : %msg%n'

# Server properties
server:
  port: ${SERVICE_PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store: file:./app-keystore.jks
    key-store-password: changeme
    key-alias: client
    key-password: changeme
    trust-store: file:./app-truststore.jks
    trust-store-password: changeme
    client-auth: ${MTLS_STATUS}